# Generated by Django 2.0.13 on 2019-03-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IeData',
            fields=[
                ('ie_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_name', models.CharField(max_length=30)),
                ('phy_type', models.CharField(max_length=11)),
                ('ie_beacon', models.CharField(max_length=500)),
                ('ie_probe', models.CharField(max_length=500)),
                ('ie_auth', models.CharField(max_length=500)),
                ('ie_assoc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ie_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenap.Question'),
        ),
    ]
